import {Dish} from './dish';
export const DISHES: Dish[] = [
    {
        id:0,
        name:'Ven Pongal',
        image:"/assets/images/ven_pongal.jpg",
        category: 'breakfast&dinner',
        price:"Rs.50",
        
    },
    {
        id:1,
        name:'Idli',
        image:"/assets/images/idli.jpg",
        category: 'breakfast&dinner',
        price:"Rs.30",
    },
    {
        id:2,
        name:'Poori',
        image:"/assets/images/poori.jpg",
        category: 'breakfast&dinner',
        price:"Rs.50",
    },
    {
        id:3,
        name:'Plain Dosa',
        image:"/assets/images/dosa.jpg",
        category: 'breakfast&dinner',
        price:"Rs.45",
        
    },
    {
        id:4,
        name:'Masala Dosa',
        image:"/assets/images/masaladosa.jpg",
        category: 'breakfast&dinner',
        price:"Rs.55",
        
    },
    {
        id:5,
        name:'Rava Dosa',
        image:"/assets/images/rava.jpg",
        category: 'breakfast&dinner',
        price:"Rs.45",
        
    },
    {
        id:6,
        name:"Idiyappam",
        image:"/assets/images/idiyappam.jpg",
        category: 'breakfast&dinner',
        price:"Rs.60",
        
    },
    {
        id:7,
        name:'Vegetable Uthappam',
        image:"/assets/images/uthappam.jpg",
        category: 'breakfast&dinner',
        price:"Rs.45",
        
    },

    {
        id:8,
        name:'Sweet Pongal',
        image:"/assets/images/sweetpongal.jpg",
        category: 'breakfast&dinner',
        price:"Rs.80",
        
    },
    {
        id:9,
        name:'Kesari Bath',
        image:"/assets/images/kesari.jpg",
        category: 'breakfast&dinner',
        price:"Rs.80",
        
    },
    {
        id:10,
        name:'Fried rice',
        image:"/assets/images/friedrice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.105",   
    },
    {
        id:11,
        name:'Vegetable Biryani',
        image:"/assets/images/vegbiryani.jpg",
        category: 'breakfast&dinner',
        price:"Rs.120",   
    },
    {
        id:11,
        name:'Tomato Rice',
        image:"/assets/images/tomatorice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.100", 
    },
    {
        id:12,
        name:'Lemon Rice',
        image:"/assets/images/lemonrice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.60", 
    },
    {
        id:13,
        name:'Jeera Rice',
        image:"/assets/images/jeerarice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.65",   
    },
    {
        id:14,
        name:'Curd Rice',
        image:"/assets/images/curdrice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.50", 
    },

    {
        id:15,
        name:'Full Meals',
        image:"/assets/images/fullmeals.jpg",
        category: 'breakfast&dinner',
        price:"Rs.120",  
    },
    {
        id:16,
        name:'Chappati',
        image:"/assets/images/chappati.jpg",
        category: 'breakfast&dinner',
        price:"Rs.80",   
    },
    {
        id:17,
        name:'Parota',
        image:"/assets/images/parota.jpg",
        category: 'breakfast&dinner',
        price:"Rs.80",   
    },
    {
        id:18,
        name:'Chilli Parota',
        image:"/assets/images/chilliparota.jpg",
        category: 'breakfast&dinner',
        price:"Rs.100",   
    },
    {
        id:19,
        name:'Apple Juice',
        image:"/assets/images/applejuice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.100",   
    },
    {
        id:20,
        name:'Pomegranate Juice',
        image:"/assets/images/pomegranatejuice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.90",   
    },
    {
        id:21,
        name:'Orange Juice',
        image:"/assets/images/orangejuice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.80",   
    },
    {
        id:22,
        name:'Mosambi  Juice',
        image:"/assets/images/mosambijuice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.75",   
    },
    {
        id:23,
        name:'Lemon Juice',
        image:"/assets/images/lemonjuice.jpg",
        category: 'breakfast&dinner',
        price:"Rs.50",   
    },
    {
        id:24,
        name:'Butter Milk',
        image:"/assets/images/buttermilk.jpg",
        category: 'breakfast&dinner',
        price:"Rs.30",   
    },
    //Shakes
    {
        id:25,
        name:'Vanilla Milkshake',
        image:"/assets/images/vanilla.jpg",
        category: 'breakfast&dinner',
        price:"Rs.130",   
    },
    {
        id:26,
        name:'Strawberry Milkshake',
        image:"/assets/images/strawberry.jpg",
        category: 'breakfast&dinner',
        price:"Rs.130",   
    },
    {
        id:27,
        name:'Butterscotch Milkshake',
        image:"/assets/images/butterscotch.jpg",
        category: 'breakfast&dinner',
        price:"Rs.135",   
    },
    {
        id:28,
        name:'Chocolate Milkshake',
        image:"/assets/images/chocolate.jpg",
        category: 'breakfast&dinner',
        price:"Rs.130",   
    },
    //Hot beverage
    {
        id:29,
        name:'Milk',
        image:"/assets/images/milk.jpg",
        category: 'breakfast&dinner',
        price:"Rs.20",   
    },
    {
        id:30,
        name:'Tea',
        image:"/assets/images/tea.jpg",
        category: 'breakfast&dinner',
        price:"Rs.25",   
    },
    {
        id:31,
        name:'Coffee',
        image:"/assets/images/coffee.jpg",
        category: 'breakfast&dinner',
        price:"Rs.30",   
    },
    {
        id:32,
        name:'Badam Milk',
        image:"/assets/images/badammilk.jpg",
        category: 'breakfast&dinner',
        price:"Rs.35",   
    },

    //Starters
    {
        id:33,
        name:'Paneer 65',
        image:"/assets/images/paneer65.jpg",
        category: 'breakfast&dinner',
        price:"Rs.135",   
    },  
    {
        id:34,
        name:'Paneer tikka',
        image:"/assets/images/paneertikka.jpg",
        category: 'breakfast&dinner',
        price:"Rs.145",   
    },  
    {
        id:35,
        name:'Paneer Manchurian',
        image:"/assets/images/paneermanchurian.jpg",
        category: 'breakfast&dinner',
        price:"Rs.125",   
    }, 
    {
        id:36,
        name:'Gobi Manchurian',
        image:"/assets/images/gobimanchurian.jpg",
        category: 'breakfast&dinner',
        price:"Rs.105",   
    },
    {
        id:37,
        name:'Gobi 65',
        image:"/assets/images/gobi65.jpg",
        category: 'breakfast&dinner',
        price:"Rs.100",   
    },
    {
        id:38,
        name:'Veg Manchurian',
        image:"/assets/images/vegmanchurian.jpg",
        category: 'breakfast&dinner',
        price:"Rs.135",   
    },  
    {
        id:39,
        name:'Baby Corn Manchurian',
        image:"/assets/images/babycornmanchurian.jpg",
        category: 'breakfast&dinner',
        price:"Rs.145",   
    }, 
    {
        id:40,
        name:'Spring Roll',
        image:"/assets/images/springroll.jpg",
        category: 'breakfast&dinner',
        price:"Rs.125",   
    },
    {
        id:41,
        name:'French Fries',
        image:"/assets/images/frenchfries.jpg",
        category: 'breakfast&dinner',
        price:"Rs.105",   
    },
    {
        id:42,
        name:'Smilies',
        image:"/assets/images/smilies.jpg",
        category: 'breakfast&dinner',
        price:"Rs.95",   
    },
    //Dinner Special
    {
        id:43,
        name:'Appam',
        image:"/assets/images/appam.jpg",
        category: 'dinner',
        price:"Rs.60",   
    },
    {
        id:44,
        name:'Mini idli',
        image:"/assets/images/miniidli.jpg",
        category: 'dinner',
        price:"Rs.40",   
    },
    {
        id:45,
        name:'Chola Poori',
        image:"/assets/images/cholapoori.jpg",
        category: 'dinner',
        price:"Rs.80",   
    },
    {
        id:46,
        name:'Paniyaram',
        image:"/assets/images/paniyaram.jpg",
        category: 'dinner',
        price:"Rs.50",   
    },
    {
        id:47,
        name:'Adai',
        image:"/assets/images/adai.jpg",
        category: 'dinner',
        price:"Rs.80",   
    },
    {
        id:48,
        name:'Phulka',
        image:"/assets/images/phulka.jpg",
        category: 'dinner',
        price:"Rs.70",   
    },
    {
        id:49,
        name:'Naan',
        image:"/assets/images/Naan.jpg",
        category: 'dinner',
        price:"Rs.105",   
    },
    {
        id:50,
        name:'kulcha',
        image:"/assets/images/khulcha.jpg",
        category: 'dinner',
        price:"Rs.115",   
    },
    {
        id:51,
        name:'Noodles',
        image:"/assets/images/noodles.jpg",
        category: 'dinner',
        price:"Rs.90",   
    },
    {
        id:52,
        name:'Mini tiffin',
        image:"/assets/images/minitiffin.jpg",
        category: 'dinner',
        price:"Rs.150",   
    },
    //Sweets
    {
        id:53,
        name:'Gulab Jamoon',
        image:"/assets/images/jamoon.jpg",
        category: 'dinner',
        price:"Rs.50",   
    },
    {
        id:54,
        name:'Rasamalai',
        image:"/assets/images/rasamalai.jpg",
        category: 'dinner',
        price:"Rs.70",   
    },
    {
        id:55,
        name:'Rasagulla',
        image:"/assets/images/rasagulla.jpg",
        category: 'dinner',
        price:"Rs.65",   
    },
    {
        id:56,
        name:'Basundi',
        image:"/assets/images/basundi.jpg",
        category: 'dinner',
        price:"Rs.60",   
    },
];